### ISSUE TITLE
circom `for` loop results in error when running MP-SPDZ  

### ISSUE THREAD

**Issue by mhchia** [ZKStats/zk-stats-lib#26]
## What's wrong?
As mentioned in https://github.com/ZKStats/zk-stats-lib/blob/c18e1eca02ad695d8af25396f02b2b08818ca5df/zkstats/onnx2circom/mpc.circom#L102-L123, in the #25 , MP-SPDZ doesn't execute correctly with circom loops sometimes. 

### Reproduce
Modify code here: https://github.com/ZKStats/zk-stats-lib/blob/b2385701f5aa4ef6b1b88c22167aae879c004ea7/zkstats/onnx2circom/mpc.circom#L102-L107
Uncomment the for loop and comment the unrolled code
```circom
    component k_by_sum = TFReduceSum(upper_bound);
    for (var i = 0; i < upper_bound; i++) {
        k_by_sum.in[i][0] <== sel[i] * i;
    }
    // k_by_sum.in[0][0] <== sel[0] * 0;
    // k_by_sum.in[1][0] <== sel[1] * 1;
    // k_by_sum.in[2][0] <== sel[2] * 2;
    // k_by_sum.in[3][0] <== sel[3] * 3;
    // k_by_sum.in[4][0] <== sel[4] * 4;
    // k_by_sum.in[5][0] <== sel[5] * 5;
    // k_by_sum.in[6][0] <== sel[6] * 6;
    // k_by_sum.in[7][0] <== sel[7] * 7;
    // k_by_sum.in[8][0] <== sel[8] * 8;
    // k_by_sum.in[9][0] <== sel[9] * 9;
    // k_by_sum.in[10][0] <== sel[10] * 10;
    // k_by_sum.in[11][0] <== sel[11] * 11;
    // k_by_sum.in[12][0] <== sel[12] * 12;
    // k_by_sum.in[13][0] <== sel[13] * 13;
    // k_by_sum.in[14][0] <== sel[14] * 14;
    // k_by_sum.in[15][0] <== sel[15] * 15;
```
Run the test
```bash
pytest -s tests/onnx2circom/test_onnx_to_circom.py
```
You'll get an error like this
```bash
!@# compile: gate line= ['2', '1', '44', '43', '53', 'AAdd']
!@# compile: gate line= ['2', '1', '21', '45', '55', 'AMul']
Traceback (most recent call last):
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/compile-run.py", line 14, in <module>
    prog = compiler.compile_file()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/compilerLib.py", line 452, in compile_file
    exec(compile(infile.read(), infile.name, "exec"), self.VARS)
  File "Programs/Source/model.mpc", line 4, in <module>
    outputs = circuit(inputs)
              ^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/../Compiler/circuit_arith.py", line 88, in __call__
    return self.run(*inputs)
           ^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/../Compiler/circuit_arith.py", line 99, in run
    flat_res = self.functions[n](*combined_inputs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/library.py", line 374, in __call__
    self.on_first_call(wrapped_function)
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/library.py", line 440, in on_first_call
    result = wrapped_function(*self.compile_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/library.py", line 373, in wrapped_function
    return self.function(*(list(compile_args) + runtime_args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/../Compiler/circuit_arith.py", line 97, in <lambda>
    self.compile(*args))
    ^^^^^^^^^^^^^^^^^^^
  File "/Users/mhchia/projects/work/pse/MP-SPDZ/Scripts/../Compiler/../Compiler/circuit_arith.py", line 186, in compile
    wires[int(line[4])] = ins[0] * ins[1]
                          ~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for *: 'sint' and 'NoneType'
```

## How to fix it?
It's possible doing with
- we're not using the latest circom-2-arithc
- our MP-SPDZ bristol parser (zkstats/arithc_to_bristol.py) or loader (zkstats/backends/mpspdz.py) has bug

We should investigate this bit so that we can use for loops in circom safely

**Comment by mhchia** [comment]
Closed by #27
